CI Workflow: Fix black error (#168)
When running an unsuccessful `black` format check the script automatically runs the formatter and commits the altered source code.

This currently results in an error:
```
Run black src tests
reformatted src/chia_log/log_consumer.py
All done! ✨ 🍰 ✨
1 file reformatted, 62 files left unchanged.
error: pathspec 'feature/improve-harvester-offline' did not match any file(s) known to git
Error: Process completed with exit code 1.
```

Moved the black format check to the back of the queue, as it can be automatically fixed, while the others require manual intervention.

Also removed the `black --check` since we want to make the changes anyhow